languages:
  JavaScript: true
  Python: true

exclude_paths:
- "siteblocks/runtests.py"
- "siteblocks/tests.py"
- "siteblocks/tests/*"
- "siteblocks/migrations/*"
- "siteblocks/south_migrations/*"
- "docs/*"
